[package]
name = "cosmic-switch-less"
version = "0.2.1"
edition = "2024"
license = "MPL-2.0"
description = "An alternative app switcher for COSMIC Desktop that only shows windows from the *current* workspace."
repository = "https://github.com/riverfr0zen/cosmic-switch-less"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
wayland-client = "0.31"
calloop = "0.14"
calloop-wayland-source = "0.4"
cosmic-protocols = { git = "https://github.com/pop-os/cosmic-protocols", features = ["client"] }
cctk = { package = "cosmic-client-toolkit", git = "https://github.com/pop-os/cosmic-protocols" }
freedesktop-desktop-entry = "0.7"
serde = { version = "1", features = ["derive"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
# See https://github.com/pop-os/libcosmic/blob/master/Cargo.toml for available features.
# Remove features if not needed.
features = [
    # GPU-accelerated rendering
    "wgpu",
    # Wayland layer-shell + cctk-gated platform_specific modules
    "wayland",
]

# Uncomment to test a locally-cloned libcosmic
# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }
